version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Example Laravel Docker production image...
      - docker build --target prod -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/example-laravel:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/example-laravel:latest
      - echo Creating Dockerrun.aws.json...
      - |
        printf '{"AWSEBDockerrunVersion": "1","Image": { "Name": "%s.dkr.ecr.%s.amazonaws.com/example-laravel:latest","Update": "true" },"Ports": [ { "ContainerPort": "80" } ],"Logging": "/var/log/nginx" }' $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION > Dockerrun.aws.json


artifacts:
  files:
    - Dockerrun.aws.json
