version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Example Laravel Docker test image...
      - docker build --target test -t example-laravel:test .
      - echo Running tests...
      - docker run example-laravel:test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Building the Example Laravel Docker production image...
      - docker build --target prod -t example-laravel:latest .
      - echo Saving the Docker image to a tar file...
      - docker save example-laravel:latest > example-laravel.tar
      - echo Packaging the Docker image and Dockerrun.aws.json into a zip file...
      - zip -r example-laravel.zip example-laravel.tar Dockerrun.aws.json

artifacts:
  files:
    - example-laravel.zip
